version: 2.1

jobs:
  build:
    docker:
      - image: orgesified/plucky:latest
    steps:
      - checkout
      - run:
          name: "get clang"
          command: "git clone --depth=1 --single-branch https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone ~/.local/clang"
      - run:
          name: "build"
          command: "./build.sh cidebug+cla+llvm+upload+pix+tel"

workflows:
  build-workflow:
    jobs:
      - build
